"""Email updates

Revision ID: 6a2efc896fbd
Revises: 68c266563efa
Create Date: 2026-02-10 20:49:37.356380

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6a2efc896fbd'
down_revision: str | Sequence[str] | None = '68c266563efa'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('to_emails', sa.String(length=1000), nullable=True))
    op.alter_column('emails', 'edition_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('emails', 'email_alias_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('emails', 'email_alias_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('emails', 'edition_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('emails', 'to_emails')
    # ### end Alembic commands ###
